services:
  dev:
    build:
      context: .
      target: development
    restart: unless-stopped
    # networks:
    #   - coolify
    ports:
      - 3000:3000
    develop:
      watch:
        - action: rebuild
          path: .eleventy.js
          # path: index.js
          ignore:
            - src/
        - action: sync
          path: src/
          target: /app/src
  prod:
    build:
      context: .
      target: production
    restart: unless-stopped
    # networks:
    #   - coolify
    ports:
      - 3000:3000
