services:
  prologue:
    container_name: prologue
    build: .
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 3000:3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.scrinium.rule=Host(`scrinium.daedalist.net`)
      #- traefik.http.routers.scrinium.entrypoints=https
      #- traefik.http.routers.scrinium.tls=true
      - traefik.http.services.scrinium.loadbalancer.server.port=80
networks:
  proxy:
    external: true
