services:
  prologue:
    container_name: prologue
    build:
      context: .
      target: development
    restart: unless-stopped
    # networks:
    #   - coolify
    ports:
      - 3000:3000
    develop:
      watch:
        - action: rebuild
          path: .
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.middlewares.gzip.compress=true
    #   - traefik.http.routers.scrinium.rule=Host(`scrinium.daedalist.net`) && PathPrefix(`/`)
    #   - traefik.http.routers.scrinium.entrypoints=http
    #   - traefik.http.routers.scrinium.service=scrinium
    #   - traefik.http.routers.scrinium.middlewares=gzip
    #   - traefik.http.services.scrinium.loadbalancer.server.port=3000
# networks:
#   coolify:
#     external: true
